package tsgen

import (
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/FumingPower3925/stdocs/internal/schema"
	"github.com/FumingPower3925/stdocs/internal/spec"
)

// emit renders the whole module. Everything is sorted, so the output
// is deterministic across rebuilds and processes.
func emit(in spec.SpecInput) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by stdocs (github.com/FumingPower3925/stdocs/tsgen). DO NOT EDIT.\n")
	title := in.Info.Title
	if title == "" {
		title = "API"
	}
	fmt.Fprintf(&b, "// %s", title)
	if in.Info.Version != "" {
		fmt.Fprintf(&b, " %s", in.Info.Version)
	}
	b.WriteString(" — contract types for the OpenAPI document.\n")

	emitComponents(&b, in.Components)
	emitOperations(&b, in.Paths)
	emitWebhooks(&b, in.Webhooks)
	return []byte(b.String())
}

// emitComponents writes one exported declaration per component plus
// the components interface gluing them together.
func emitComponents(b *strings.Builder, comps map[string]*schema.Schema) {
	names := make([]string, 0, len(comps))
	for name := range comps {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		s := comps[name]
		b.WriteString("\n")
		writeJSDoc(b, "", jsdocFor(s))
		if s != nil && s.Type == "object" && s.AdditionalProperties == nil && (len(s.Properties) > 0 || !s.Nullable) {
			// Objects with fixed keys read best as interfaces; a
			// nullable component cannot be an interface, so it falls
			// through to an alias below.
			if !s.Nullable {
				fmt.Fprintf(b, "export interface %s ", name)
				writeObjectBody(b, "", s)
				b.WriteString("\n")
				continue
			}
		}
		fmt.Fprintf(b, "export type %s = %s;\n", name, typeExpr("", s, true))
	}
	if len(names) == 0 {
		return
	}
	b.WriteString("\nexport interface components {\n")
	for _, name := range names {
		fmt.Fprintf(b, "\t%s: %s;\n", memberName(name), name)
	}
	b.WriteString("}\n")
}

// emitOperations writes the operations interface, keyed by the
// document's stable operationIds.
func emitOperations(b *strings.Builder, paths []spec.PathItem) {
	type entry struct {
		op     *spec.Operation
		path   string
		shared []spec.Param
	}
	byID := map[string]entry{}
	ids := make([]string, 0, 16)
	for _, item := range paths {
		for _, op := range item.Operations {
			if op == nil || op.OperationID == "" {
				continue
			}
			if _, dup := byID[op.OperationID]; !dup {
				ids = append(ids, op.OperationID)
			}
			byID[op.OperationID] = entry{op: op, path: item.Path, shared: item.Parameters}
		}
	}
	if len(ids) == 0 {
		return
	}
	sort.Strings(ids)
	b.WriteString("\nexport interface operations {\n")
	for _, id := range ids {
		e := byID[id]
		writeJSDoc(b, "\t", opJSDoc(e.op, e.path))
		fmt.Fprintf(b, "\t%s: {\n", memberName(id))
		writeParameters(b, e.op.Parameters, e.shared)
		if rb := e.op.RequestBody; rb != nil {
			opt := ""
			if !rb.Required {
				opt = "?"
			}
			writeJSDoc(b, "\t\t", jsdocFor(rb.Schema))
			fmt.Fprintf(b, "\t\trequestBody%s: %s;\n", opt, typeExpr("\t\t", rb.Schema, false))
		}
		writeResponses(b, e.op.Responses)
		b.WriteString("\t};\n")
	}
	b.WriteString("}\n")
}

// emitWebhooks writes the webhooks interface when webhooks exist.
func emitWebhooks(b *strings.Builder, hooks map[string]spec.Webhook) {
	if len(hooks) == 0 {
		return
	}
	names := make([]string, 0, len(hooks))
	for name := range hooks {
		names = append(names, name)
	}
	sort.Strings(names)
	b.WriteString("\nexport interface webhooks {\n")
	for _, name := range names {
		h := hooks[name]
		var doc []string
		if h.Summary != "" {
			doc = append(doc, h.Summary)
		}
		if h.Description != "" {
			doc = append(doc, h.Description)
		}
		writeJSDoc(b, "\t", doc)
		fmt.Fprintf(b, "\t%s: {\n", memberName(name))
		if rb := h.RequestBody; rb != nil {
			opt := ""
			if !rb.Required {
				opt = "?"
			}
			fmt.Fprintf(b, "\t\trequestBody%s: %s;\n", opt, typeExpr("\t\t", rb.Schema, false))
		}
		writeResponses(b, h.Responses)
		b.WriteString("\t};\n")
	}
	b.WriteString("}\n")
}

// writeParameters groups an operation's parameters by location. A
// group is optional only when every member is.
func writeParameters(b *strings.Builder, own, shared []spec.Param) {
	merged := make([]spec.Param, 0, len(own)+len(shared))
	seen := map[string]bool{}
	for _, p := range append(append([]spec.Param{}, own...), shared...) {
		key := p.In + "\x00" + p.Name
		if seen[key] {
			continue // operation-level wins over path-level
		}
		seen[key] = true
		merged = append(merged, p)
	}
	if len(merged) == 0 {
		return
	}
	b.WriteString("\t\tparameters: {\n")
	for _, in := range []string{"path", "query", "header", "cookie"} {
		var group []spec.Param
		allOpt := true
		for _, p := range merged {
			if p.In != in {
				continue
			}
			group = append(group, p)
			if p.Required {
				allOpt = false
			}
		}
		if len(group) == 0 {
			continue
		}
		sort.Slice(group, func(i, j int) bool { return group[i].Name < group[j].Name })
		opt := ""
		if allOpt {
			opt = "?"
		}
		fmt.Fprintf(b, "\t\t\t%s%s: {\n", in, opt)
		for _, p := range group {
			var doc []string
			if p.Description != "" {
				doc = append(doc, p.Description)
			}
			writeJSDoc(b, "\t\t\t\t", append(doc, constraintDoc(p.Schema)...))
			req := "?"
			if p.Required {
				req = ""
			}
			fmt.Fprintf(b, "\t\t\t\t%s%s: %s;\n", memberName(p.Name), req, typeExpr("\t\t\t\t", p.Schema, false))
		}
		b.WriteString("\t\t\t};\n")
	}
	b.WriteString("\t\t};\n")
}

// writeResponses maps each documented status to its body type;
// body-less entries type as undefined. Numeric keys sort ascending
// with "default" last.
func writeResponses(b *strings.Builder, resps map[string]*spec.Response) {
	keys := make([]string, 0, len(resps))
	for key := range resps {
		keys = append(keys, key)
	}
	sort.Slice(keys, func(i, j int) bool {
		ni, ei := strconv.Atoi(keys[i])
		nj, ej := strconv.Atoi(keys[j])
		if (ei == nil) != (ej == nil) {
			return ei == nil // numbers before "default"
		}
		if ei == nil {
			return ni < nj
		}
		return keys[i] < keys[j]
	})
	if len(keys) == 0 {
		return
	}
	b.WriteString("\t\tresponses: {\n")
	for _, key := range keys {
		resp := resps[key]
		member := key
		if _, err := strconv.Atoi(key); err != nil {
			member = memberName(key)
		}
		if resp == nil || resp.Schema == nil {
			fmt.Fprintf(b, "\t\t\t%s: undefined;\n", member)
			continue
		}
		writeJSDoc(b, "\t\t\t", jsdocFor(resp.Schema))
		fmt.Fprintf(b, "\t\t\t%s: %s;\n", member, typeExpr("\t\t\t", resp.Schema, false))
	}
	b.WriteString("\t\t};\n")
}

// writeObjectBody renders an object schema's fixed-key body
// ({ a: T; b?: U }) at the given indentation.
func writeObjectBody(b *strings.Builder, indent string, s *schema.Schema) {
	if len(s.Properties) == 0 {
		b.WriteString("{}")
		return
	}
	required := make(map[string]bool, len(s.Required))
	for _, name := range s.Required {
		required[name] = true
	}
	names := make([]string, 0, len(s.Properties))
	for name := range s.Properties {
		names = append(names, name)
	}
	sort.Strings(names)
	b.WriteString("{\n")
	inner := indent + "\t"
	for _, name := range names {
		p := s.Properties[name]
		writeJSDoc(b, inner, jsdocFor(p))
		opt := "?"
		if required[name] {
			opt = ""
		}
		fmt.Fprintf(b, "%s%s%s: %s;\n", inner, memberName(name), opt, typeExpr(inner, p, false))
	}
	b.WriteString(indent + "}")
}

// typeExpr renders a schema as a TypeScript type expression. The
// model is closed — no oneOf/allOf/anyOf exist in it — so this
// mapping is exhaustive. topLevel suppresses the nullable union for
// callers that handle it themselves.
func typeExpr(indent string, s *schema.Schema, topLevel bool) string {
	base := baseType(indent, s)
	if s != nil && s.Nullable && !topLevel {
		return base + " | null"
	}
	return base
}

func baseType(indent string, s *schema.Schema) string {
	if s == nil {
		return "unknown"
	}
	if s.Ref != "" {
		return strings.TrimPrefix(s.Ref, "#/components/schemas/")
	}
	if len(s.Enum) > 0 {
		parts := make([]string, len(s.Enum))
		for i, v := range s.Enum {
			parts[i] = jsonLiteral(v)
		}
		return strings.Join(parts, " | ")
	}
	switch s.Type {
	case "string":
		return "string"
	case "integer", "number":
		return "number"
	case "boolean":
		return "boolean"
	case "null":
		return "null"
	case "array":
		elem := typeExpr(indent, s.Items, false)
		if strings.ContainsAny(elem, "|{ ") {
			return "(" + elem + ")[]"
		}
		return elem + "[]"
	case "object":
		if s.AdditionalProperties != nil {
			return "Record<string, " + typeExpr(indent, s.AdditionalProperties, false) + ">"
		}
		if len(s.Properties) > 0 {
			var b strings.Builder
			writeObjectBody(&b, indent, s)
			return b.String()
		}
		return "Record<string, never>"
	}
	// No type constraint: interfaces, json.RawMessage, custom
	// marshalers. The wire format is honest-unknown, except the
	// json-string-encoded wrapper, which is a string by construction.
	if marker, ok := s.Extensions["x-stdocs-type"].(string); ok {
		if strings.HasPrefix(marker, "json-string-encoded ") {
			return "string"
		}
		return "unknown /* Go: " + sanitizeComment(marker) + " */"
	}
	return "unknown"
}

// jsdocFor collects a schema's JSDoc lines: the description (the
// generated package-path fallback never leaks into TypeScript) plus
// the constraint facets.
func jsdocFor(s *schema.Schema) []string {
	if s == nil {
		return nil
	}
	var lines []string
	if s.Description != "" && !strings.HasPrefix(s.Description, "Generated from Go type ") {
		lines = append(lines, s.Description)
	}
	return append(lines, constraintDoc(s)...)
}

// constraintDoc renders the constraint facets as JSDoc tag lines.
func constraintDoc(s *schema.Schema) []string {
	if s == nil {
		return nil
	}
	var lines []string
	add := func(tag, value string) {
		if value != "" {
			lines = append(lines, "@"+tag+" "+value)
		}
	}
	if s.Format != "" {
		add("format", s.Format)
	}
	add("minimum", string(s.Minimum))
	add("maximum", string(s.Maximum))
	add("exclusiveMinimum", string(s.ExclusiveMinimum))
	add("exclusiveMaximum", string(s.ExclusiveMaximum))
	if s.MinLength != nil {
		add("minLength", strconv.FormatUint(*s.MinLength, 10))
	}
	if s.MaxLength != nil {
		add("maxLength", strconv.FormatUint(*s.MaxLength, 10))
	}
	if s.Pattern != "" {
		add("pattern", s.Pattern)
	}
	if s.MinItems != nil {
		add("minItems", strconv.FormatUint(*s.MinItems, 10))
	}
	if s.MaxItems != nil {
		add("maxItems", strconv.FormatUint(*s.MaxItems, 10))
	}
	if s.UniqueItems {
		lines = append(lines, "@uniqueItems")
	}
	if s.Default != nil {
		add("default", jsonLiteral(s.Default))
	}
	if s.Example != nil {
		add("example", jsonLiteral(s.Example))
	}
	return lines
}

// opJSDoc collects an operation's JSDoc lines: summary, description,
// the route itself, and the deprecation marker.
func opJSDoc(op *spec.Operation, path string) []string {
	var lines []string
	if op.Summary != "" {
		lines = append(lines, op.Summary)
	}
	if op.Description != "" {
		lines = append(lines, op.Description)
	}
	lines = append(lines, op.Method+" "+path)
	if op.Deprecated {
		lines = append(lines, "@deprecated")
	}
	return lines
}

// writeJSDoc renders lines as a JSDoc block at the given indent.
// Empty input writes nothing; a single line stays on one line.
func writeJSDoc(b *strings.Builder, indent string, lines []string) {
	clean := lines[:0:0]
	for _, l := range lines {
		if l = strings.TrimRight(sanitizeComment(l), " "); l != "" {
			clean = append(clean, l)
		}
	}
	if len(clean) == 0 {
		return
	}
	if len(clean) == 1 {
		fmt.Fprintf(b, "%s/** %s */\n", indent, clean[0])
		return
	}
	fmt.Fprintf(b, "%s/**\n", indent)
	for _, l := range clean {
		fmt.Fprintf(b, "%s * %s\n", indent, l)
	}
	fmt.Fprintf(b, "%s */\n", indent)
}

// sanitizeComment keeps user text from terminating the comment it
// lives in.
func sanitizeComment(text string) string {
	text = strings.ReplaceAll(text, "*/", "*\\/")
	return strings.ReplaceAll(text, "\n", " ")
}

// jsonLiteral renders a Go value as the JSON literal TypeScript
// shares; the fallback for unmarshalable values is a quoted string.
func jsonLiteral(v any) string {
	raw, err := json.Marshal(v)
	if err != nil {
		return strconv.Quote(fmt.Sprintf("%v", v))
	}
	return string(raw)
}

// memberName quotes a member name when it is not a valid TypeScript
// identifier. Keywords are fine as members; only the character set
// matters.
func memberName(name string) string {
	if name == "" {
		return `""`
	}
	for i, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r == '_', r == '$':
		case r >= '0' && r <= '9':
			if i == 0 {
				return strconv.Quote(name)
			}
		default:
			return strconv.Quote(name)
		}
	}
	return name
}
