// Code generated by stdocs (devel) (github.com/FumingPower3925/stdocs/tsgen). DO NOT EDIT.
// Corpus API 1.2.3 — contract types for the OpenAPI document.

export interface CorpusEmpty {}

export interface CorpusError {
	/** @format int64 */
	code: number;
	message: string;
}

export interface CorpusEvent {
	kind: "created" | "deleted";
}

export interface CorpusPage_CorpusTask {
	cursor?: string;
	items: CorpusTask[];
}

export interface CorpusTask {
	anything?: unknown /* Go: interface */;
	/** @format byte */
	blob?: string;
	/**
	 * Backend-driven form schema
	 * @example {"properties":{"host":{"type":"string"}},"type":"object"}
	 */
	config_schema?: Record<string, unknown>;
	count: string;
	/** @format date-time */
	due_at: string | null;
	/** Stable identifier */
	id: string;
	labels?: Record<string, number>;
	/** @format int64 */
	level: 1 | 2 | 3;
	links?: (NamedRef | null)[];
	note: string | null;
	parent?: CorpusTask | null;
	/**
	 * @format int64
	 * @minimum 1
	 * @maximum 5
	 * @example 2
	 */
	priority: number;
	/**
	 * @format double
	 * @exclusiveMinimum 0
	 * @exclusiveMaximum 1.5
	 */
	ratio: number;
	raw?: unknown /* Go: json.RawMessage */;
	/** @default "pending" */
	status: "pending" | "active" | "done";
	/**
	 * @minItems 1
	 * @uniqueItems
	 */
	tags?: string[];
	/**
	 * @minLength 1
	 * @maxLength 200
	 * @pattern ^.+$
	 */
	title: string;
	/** Hyphens need quoting *\/ and comments need escaping */
	"weird-key"?: string;
}

export interface NamedRef {
	kind: string;
}

export interface components {
	CorpusEmpty: CorpusEmpty;
	CorpusError: CorpusError;
	CorpusEvent: CorpusEvent;
	CorpusPage_CorpusTask: CorpusPage_CorpusTask;
	CorpusTask: CorpusTask;
	NamedRef: NamedRef;
}

export interface operations {
	/**
	 * Method-less ping
	 * /ping
	 */
	any_ping: {
		responses: {
			200: undefined;
			500: CorpusError;
			/** @contentType text/plain */
			503: string;
		};
	};
	/**
	 * Delete a task
	 * DELETE /tasks/{id}
	 * @deprecated
	 */
	delete_tasks_by_id: {
		parameters: {
			path: {
				id: string;
			};
		};
		responses: {
			204: undefined;
			500: CorpusError;
			/** @contentType text/plain */
			503: string;
		};
	};
	/**
	 * Closed empty object
	 * GET /empty
	 */
	get_empty: {
		responses: {
			200: CorpusEmpty;
			500: CorpusError;
			/** @contentType text/plain */
			503: string;
		};
	};
	/**
	 * Export CSV
	 * GET /export
	 */
	get_export: {
		responses: {
			/**
			 * @contentType text/csv
			 * @header Content-Disposition — Suggested download filename
			 */
			200: string;
			500: CorpusError;
			/** @contentType text/plain */
			503: string;
		};
	};
	/**
	 * List tasks
	 * GET /tasks
	 */
	get_tasks: {
		parameters: {
			query?: {
				/** Opaque cursor */
				cursor?: string;
				/**
				 * @format int64
				 * @minimum 1
				 * @maximum 100
				 * @default 20
				 */
				limit?: number;
			};
			header?: {
				"X-Trace-Id"?: string;
			};
			cookie?: {
				theme?: string;
			};
		};
		responses: {
			200: CorpusPage_CorpusTask;
			500: CorpusError;
			/** @contentType text/plain */
			503: string;
		};
	};
	/**
	 * Get one task
	 * GET /tasks/{id}
	 */
	get_tasks_by_id: {
		parameters: {
			path: {
				id: string;
			};
		};
		responses: {
			200: CorpusTask;
			404: undefined;
			500: CorpusError;
			/** @contentType text/plain */
			503: string;
		};
	};
	/**
	 * Import an archive
	 * POST /import
	 */
	post_import: {
		requestBody: {
			/**
			 * The archive file
			 * @format binary
			 */
			archive?: string;
			/** Free-form note */
			note?: string;
		};
		responses: {
			202: undefined;
			500: CorpusError;
			/** @contentType text/plain */
			503: string;
		};
	};
	/**
	 * Create a task
	 * The long-form description survives into JSDoc.
	 * POST /tasks
	 */
	post_tasks: {
		requestBody: CorpusTask;
		responses: {
			201: CorpusTask;
			401: undefined;
			422: CorpusError;
			500: CorpusError;
			/** @contentType text/plain */
			503: string;
		};
	};
}

export interface webhooks {
	/** Task lifecycle event */
	"task-event": {
		requestBody: CorpusEvent;
		responses: {
			200: undefined;
		};
	};
}
